name: Deploy StreamFlix to Azure VM

on:
  push:
    branches:
      - build  # Kyunki is repository ki default branch ka naam 'build' hai

jobs:
  deploy:
    runs-on: self-hosted  # Yeh aapki register ki hui appvm2 ko target karega

    steps:
    - name: Checkout StreamFlix Code
      uses: actions/checkout@v4

    - name: Clean Old Files and Copy StreamFlix to Nginx
      run: |
        # Purani files clear karke naya StreamFlix code /var/www/html me daalna
        sudo rm -rf /var/www/html/*
        sudo cp -r * /var/www/html/
        
    - name: Restart Nginx Web Server
      run: |
        sudo systemctl restart nginx
