name: Deploy StreamFlix to Azure VM

on:
  push:
    branches:
      - build

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout StreamFlix Code
      uses: actions/checkout@v4

    - name: Clean Old Files and Copy StreamFlix to Nginx
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r * /var/www/html/
        
    - name: Restart Nginx Web Server
      run: |
        sudo systemctl restart nginx
